#Generated SPARQL Query:
 SELECT ?person WHERE {
  ?person dbo:occupation dbr:Pathology.
  ?person rdf:type dbo:Person.
}

#SPARQL Query Results:
#{'person': {'type': 'uri', 'value': 'http://dbpedia.org/resource/Horst_Oertel'}}
#{'person': {'type': 'uri', 'value': 'http://dbpedia.org/resource/Pelayo_Correa'}}
#{'person': {'type': 'uri', 'value': 'http://dbpedia.org/resource/Charles_Powell_White'}}
#{'person': {'type': 'uri', 'value': 'http://dbpedia.org/resource/Miguel_A._Sanchez'}}
#{'person': {'type': 'uri', 'value': 'http://dbpedia.org/resource/Friedrich_Albert_von_Zenker'}}
#{'person': {'type': 'uri', 'value': 'http://dbpedia.org/resource/Theodore_Curphey'}}
#{'person': {'type': 'uri', 'value': 'http://dbpedia.org/resource/Thomas_Edward_Knowles_Stansfield'}}
#{'person': {'type': 'uri', 'value': 'http://dbpedia.org/resource/Anna_Wessels_Williams'}}
#{'person': {'type': 'uri', 'value': 'http://dbpedia.org/resource/Timothy_Richards_Lewis'}}
#{'person': {'type': 'uri', 'value': 'http://dbpedia.org/resource/W._Roger_Williams'}}
#{'person': {'type': 'uri', 'value': 'http://dbpedia.org/resource/Aldred_Scott_Warthin'}}
#{'person': {'type': 'uri', 'value': 'http://dbpedia.org/resource/John_Hughes_Bennett'}}
#{'person': {'type': 'uri', 'value': 'http://dbpedia.org/resource/Thangjam_Dhabali_Singh'}}
#{'person': {'type': 'uri', 'value': 'http://dbpedia.org/resource/Solomon_Carter_Fuller'}}
